sudo: required

language: java

cache:
  directories:
    -$HOME/google-cloud-sdk
services:
  - docker


env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

script:
  - docker build -t get-microservice .
after_success:
  - docker tag get-microservice "$DOCKER_HUB_USERNAME"/get-microservice:latest
  - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
  - docker push "$DOCKER_HUB_USERNAME"/get-microservice:latest
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./deploy.sh; fi
