apiVersion: apps/v1
kind: Deployment
metadata:
  name: GetPhotoService-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: GetPhotoService
    spec:
      containers:
        - name: GetPhotoService
          image: RSOGorenc/GetPhotoService
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
          resources:
            limits:
              cpu: 70m
            requests:
              cpu: 70m
---
apiVersion: v1
kind: Service
metadata:
  name: GetPhotoService
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: GetPhotoService