kumuluzee:
  name: catalogue
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080

  metrics:
    servlet:
      enabled: true
      mapping: /catalogue-metrics
    web-instrumentation:
      - name: catalogue-endpoint
        url-pattern: /v1/catalogue/*
#    logstash:
#      address: 192.168.0.1
#      port: 5043
#      period-s: 15
#    logs:
#      period-s: 60
#      level: INFO

config-properties:
  test: true





